name: Django Docker CI

on:
  push:
    branches: [main, jo-branch]
  pull_request:
    branches: [main, jo-branch]

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - run: |
          pip install --upgrade pip
          pip install -r MyApp/requirements.txt
          pip install flake8
          flake8 MyApp/

  lint-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v2

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t myapp-image MyApp/

  docker-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - run: docker build -t my-django-app:latest MyApp/

      # Use official Trivy GitHub Action
      - uses: aquasecurity/trivy-action@v2
        with:
          image-ref: my-django-app:latest
          severity: CRITICAL,HIGH
          ignore-unfixed: true

  push-docker:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          docker tag myapp-image ${{ secrets.DOCKER_USERNAME }}/myapp-image:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp-image:latest
