name: Django Docker CI

on:
  push:
    branches: [main, jo-branch]
  pull_request:
    branches: [main, jo-branch]

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - run: |
          pip install --upgrade pip
          pip install -r MyApp/requirements.txt
          pip install flake8
          flake8 MyApp/
        continue-on-error: true

  lint-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3
        with:
          dockerfile: MyApp/Dockerfile
        continue-on-error: true

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t myapp-image MyApp/

  docker-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        run: docker build -t my-django-app:latest MyApp/
      - uses: aquasecurity/trivy-action@v2
        with:
          image-ref: my-django-app:latest
          severity: CRITICAL,HIGH
          ignore-unfixed: true
